# Generated by Django 2.2.5 on 2019-11-16 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentinumServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentinumVentures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=250)),
                ('company_registration_number', models.IntegerField()),
                ('founding_date', models.DateField()),
                ('slogan', models.CharField(max_length=250)),
                ('pitch', models.TextField()),
                ('pitch_video_url', models.URLField()),
                ('customer_model', models.CharField(max_length=250)),
                ('percentage', models.PositiveIntegerField(null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(max_length=250)),
                ('full_address', models.CharField(max_length=250)),
                ('stage', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('interest', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Centinum Ventures',
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('interest', models.CharField(max_length=50, null=True)),
                ('patent_number', models.PositiveIntegerField(blank=True, null=True)),
                ('copyright_number', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ideas', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='ideas_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ideas',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200, null=True)),
                ('registration_number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('service_cost', models.PositiveIntegerField(default=0)),
                ('centinum_commission', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
                ('service_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centinum_services', to='portal.CentinumServices')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=250)),
                ('company_registration_number', models.IntegerField()),
                ('founding_date', models.DateField()),
                ('slogan', models.CharField(blank=True, max_length=250)),
                ('pitch', models.TextField(blank=True)),
                ('pitch_video_url', models.URLField(blank=True)),
                ('customer_model', models.CharField(max_length=250)),
                ('stake_you_are_giving_up', models.PositiveIntegerField(null=True)),
                ('minimum_financing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financing_you_are_looking_for', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(max_length=250)),
                ('full_address', models.CharField(max_length=250)),
                ('stage', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('interest', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_startup', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='business_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Startup Businesses',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ServiceTimelineChats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_chats', to='portal.Services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service Timeline Chats',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ServiceProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=200, null=True)),
                ('registration_number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('service_description', models.TextField(null=True)),
                ('service_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categ', to='portal.ServiceCategories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('s_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnersPaymentNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', djrichtextfield.models.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_pay', to='portal.Partners')),
            ],
            options={
                'verbose_name_plural': 'Partners Payment Notes',
            },
        ),
        migrations.AddField(
            model_name='partners',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='portal.ServiceCategories'),
        ),
        migrations.AddField(
            model_name='partners',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IdeaTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_idea', to='portal.Ideas')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_idea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Idea Teams',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='IdeaInvestments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_idea', to='portal.Ideas')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_idea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Idea Investments',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='GroupChats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=1000)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to='portal.StartupBusiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Group Chats',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='BusinessTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_business', to='portal.StartupBusiness')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Teams',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BusinessInvestments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_business', to='portal.StartupBusiness')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Investments',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BusinessImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/business/%Y/%m/%d')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_images', to='portal.StartupBusiness')),
            ],
            options={
                'verbose_name_plural': 'Business Images',
            },
        ),
    ]
