# Generated by Django 2.2.5 on 2019-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20191123_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupbusiness',
            name='company_registration_number',
            field=models.PositiveIntegerField(),
        ),
    ]
