# Generated by Django 2.2.5 on 2019-11-23 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0007_auto_20191124_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaDirectInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_you_are_giving_up', models.PositiveIntegerField(null=True)),
                ('minimum_financing', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('financing_you_are_looking_for', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('number_of_investors', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Ideas')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
