# Generated by Django 2.2.5 on 2019-11-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20191124_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinvestments',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideainvestments',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
