# Generated by Django 2.2.5 on 2019-11-24 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0012_remove_businessinvestments_investor_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatsIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=1000)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chats_idea', to='portal.Ideas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_chat_idea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Group Chats',
                'ordering': ('created',),
            },
        ),
    ]
