# Generated by Django 2.2.5 on 2019-11-25 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20191125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdirectinvestors',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_biz_invest', to='portal.StartupBusiness'),
        ),
        migrations.AlterField(
            model_name='businessdirectinvestors',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideadirectinvestors',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_idea_invest', to='portal.Ideas'),
        ),
        migrations.AlterField(
            model_name='ideadirectinvestors',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
