# Generated by Django 2.2.5 on 2019-11-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191118_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.PlanCategories'),
        ),
    ]
